FROM ghcr.io/ggml-org/llama.cpp:full-cuda

RUN apt-get update && apt-get install -y python3-pip && rm -rf /var/lib/apt/lists/*
RUN pip3 install huggingface_hub --break-system-packages

COPY entrypoint.llama_cpp.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]